myna65_elixir:
    resource: "@Myna65ElixirBundle/Resources/config/routes.yml"
    type:     rest
    prefix:   /api

NelmioApiDocbundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc
